### PR TITLE
Show task result

### PR DESCRIPTION
**Pull request by mmarchetti**
### Description

If a deployment fails, show the result from Connect. This ensures that there will be an error shown even in cases where the deployment fails before the build or rendering process can be kicked off. For example, this can occur if there isn't a matching Python version available.

### Testing Notes / Validation Steps

Deploy content which requests a Python version not available at Connect. The easiest way to do this is by editing an existing manifest and using `rsconnect deploy manifest`.

### CODE REVIEW

**Review by bcwu — APPROVED** [review]

**Comment by kgartland-rstudio** [comment]
It seems the only way to see the error details is using the verbose flag.  Can we move the error to the standard error output?

Here's the response I see when I'm in verbose mode:
```
[DEBUG] 2022-03-31T12:11:10-0400 Response: 200 OK
[DEBUG] 2022-03-31T12:11:10-0400 Headers:
[DEBUG] 2022-03-31T12:11:10-0400 --> Server: nginx/1.19.10
[DEBUG] 2022-03-31T12:11:10-0400 --> Date: Thu, 31 Mar 2022 16:11:10 GMT
[DEBUG] 2022-03-31T12:11:10-0400 --> Content-Type: application/json; charset=utf-8
[DEBUG] 2022-03-31T12:11:10-0400 --> Content-Length: 317
[DEBUG] 2022-03-31T12:11:10-0400 --> Connection: keep-alive
[DEBUG] 2022-03-31T12:11:10-0400 --> Cache-Control: no-cache, no-store, must-revalidate
[DEBUG] 2022-03-31T12:11:10-0400 --> Expires: 0
[DEBUG] 2022-03-31T12:11:10-0400 --> Pragma: no-cache
[DEBUG] 2022-03-31T12:11:10-0400 --> Strict-Transport-Security: max-age=2592000
[DEBUG] 2022-03-31T12:11:10-0400 --> X-Content-Type-Options: nosniff
[DEBUG] 2022-03-31T12:11:10-0400 --> X-Correlation-Id: 7f12503f-8fca-4a5a-9b5a-44b6428a930e
[DEBUG] 2022-03-31T12:11:10-0400 --> {"id":"sVb6DfxJbV9Q0S3k","user_id":1,"status":["Building Dash application..."],"result":{"type":"build-failed-error","data":"An error occurred while building the content"},"finished":true,"code":1,"error":"Cannot find compatible environment: no compatible Local environment with Python version 3.6.5","last_status":1}
```

without verbose mode, i see:
```
Deployment log:
Building Dash application...
An error occurred while building the content (build-failed-error)
Task failed. Task exited with status 1.
Error: Task exited with status 1.
```

**Comment by kgartland-rstudio** [comment]
Looks good now:

One nit though.  Can we change `Local environment` to `Connect environment`?

```
Deployment log:
Building Dash application...
An error occurred while building the content (build-failed-error)
Cannot find compatible environment: no compatible Local environment with Python version 3.6.5
Error: Task exited with status 1.
```

**Comment by aronatkins** [comment]
The "Local" name is from Connect and represents that we are running code on the Connect server and not externally. That language is not from rsconnect-python.

**Comment by mmarchetti** [comment]
We could put a label on the error line saying it is from Connect if that helps.

**Comment by kgartland-rstudio** [comment]
> We could put a label on the error line saying it is from Connect if that helps.

That might help. I can just see people thinking there's something wrong with their own local environment.

**Comment by kgartland-rstudio** [comment]
Looks good!

```
Deployment log:
Building Python API...
An error occurred while building the content (build-failed-error)
Error from Connect server: Cannot find compatible environment: no compatible Local environment with Python version 3.6.12
```

**Pull request merged**
