### PR TITLE
Put all settings in pyproject.toml

### PR DESCRIPTION
**Pull request by mmarchetti**
Modernize our configuration to use pyproject.toml.

## Type of Change

- [ ] Bug Fix            
- [ ] New Feature       
- [ ] Breaking Change   
- [x] Tooling

## Automated Tests
CI passing should be sufficient.

## Directions for Reviewers
In the repo directory:
```
# create a virtualenv for this project
python -m venv ./.venv
source .venv/bin/activate

# install dev dependencies such as flake8 if you are working on the code
# (the steps below should still work without this)
pip install -r requirements.txt  

# install rsconnect-python and its runtime dependencies
# also optional test dependencies, if you want to run the tests.
pip install -e '.[test]'

# this should show the correct version
rsconnect version

# other functions should work
rsconnect deploy ...

# build for release
make dist
```

## Checklist

- [ ] I have updated [CHANGELOG.md](../CHANGELOG.md) to cover notable changes.
- [ ] I have updated all related GitHub issues to reflect their current state.

### CODE REVIEW

**Comment by tdstein** [comment]
Do you consider moving the dependencies in requirements.txt into to `project.optional-dependencies` in `pyproject.toml`?

**Comment by tdstein** [comment]
I hit an error on `make dist`:

```console
/Users/me/Code/rsconnect-python/.venv/bin/python: No module named setuptools_scm
pip wheel --no-deps -w dist .
Processing /Users/me/Code/rsconnect-python
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: rsconnect-python
  Building wheel for rsconnect-python (pyproject.toml) ... done
  Created wheel for rsconnect-python: filename=rsconnect_python-1.20.1.dev60+g9682fbd-py2.py3-none-any.whl size=110122 sha256=f6106d693f4f8f43e45473b6081c28d588f79e83c7bed4d5d4659d5327751264
  Stored in directory: /Users/me/Library/Caches/pip/wheels/b5/25/09/ad693195e3c7745af18ea3ab7193189656ff96be93de473b60
Successfully built rsconnect-python
twine check dist/rsconnect_python--py2.py3-none-any.whl
make: twine: No such file or directory
make: *** [dist] Error 1
```

**Comment by mmarchetti** [comment]
> /Users/me/Code/rsconnect-python/.venv/bin/python: No module named setuptools_scm

`setuptools_scm` is in the `requirements.txt` - did it get installed when you did the `pip install -r requirements.txt` step?

**Comment by tdstein** [comment]
> > /Users/me/Code/rsconnect-python/.venv/bin/python: No module named setuptools_scm
> 
> `setuptools_scm` is in the `requirements.txt` - did it get installed when you did the `pip install -r requirements.txt` step?

I skipped it. That should resolve the issue then.

**Comment by mmarchetti** [comment]
> Do you consider moving the dependencies in requirements.txt into to `project.optional-dependencies` in `pyproject.toml`?

I thought about it, but didn't yet - would appreciate input on this. Installing optional dependencies will also install the package (like when you run `pip install -e .[test]`). Are there cases where we want to install the tooling without installing the package? If not, we can add them to the `[test]` dependencies.

**Comment by tdstein** [comment]
> > Do you consider moving the dependencies in requirements.txt into to `project.optional-dependencies` in `pyproject.toml`?
> 
> I thought about it, but didn't yet - would appreciate input on this. Installing optional dependencies will also install the package (like when you run `pip install -e .[test]`). Are there cases where we want to install the tooling without installing the package? If not, we can add them to the `[test]` dependencies.

I'm not aware of any of those cases. In other projects, I have included build tooling within the `[test]` group, so that `pip install -e '.[test]'` gets me everything I need for local development.

**Review by tdstein — APPROVED** [review]
Validated `make dist` works with dependencies installed via `pip install -e '.[test]'`

**Pull request merged**
