### PR TITLE
Aliases 'api' commands to 'flask'.

### LINKED ISSUE #491: Suggestion: rename `rsconnect deploy api` command to `rsconnect deploy flask`
The `rsconnect deploy` command has the following options:

```bash
$ rsconnect deploy --help
Usage: rsconnect deploy [OPTIONS] COMMAND [ARGS]...

  Deploy content to Posit Connect, Posit Cloud, or shinyapps.io.

Options:
  --help  Show this message and exit.

Commands:
  api            Deploy a Python API to Posit Connect [v1.8.2+], Posit Cloud,
                 or shinyapps.io.
  bokeh          Deploy a Bokeh Application to Posit Connect [v1.8.4+], Posit
                 Cloud, or shinyapps.io.
  dash           Deploy a Dash Application to Posit Connect [v1.8.2+], Posit
                 Cloud, or shinyapps.io.
  fastapi        Deploy a Python FastAPI to Posit Connect [v2021.08.0+], Posit
                 Cloud, or shinyapps.io.
  html           Deploy html content to Posit Connect or Posit Cloud.
  manifest       Deploy content to Posit Connect, Posit Cloud, or shinyapps.io
                 by manifest.
  notebook       Deploy Jupyter notebook to Posit Connect [v1.7.0+].
  other-content  Describe deploying other content to Posit Connect.
  quarto         Deploy Quarto content to Posit Connect [v2021.08.0+] or Posit
                 Cloud.
  shiny          Deploy a Python Shiny Application to Posit Connect
                 [v2022.07.0+], Posit Cloud, or shinyapps.io.
  streamlit      Deploy a Streamlit Application to Posit Connect [v1.8.4+],
                 Posit Cloud, or shinyapps.io.
  voila          Deploy Jupyter notebook in Voila mode to Posit Connect
                 [v2023.03.0+].
```

I propose renaming `rsconnect deploy api` to `rsconnect deploy flask`.

- Now that FastAPI is supported, it is confusing that the command to deploy a flask API is called `api` (all of the other deploy commands use the framework name).
- The help message is also confusing and does not mention Flask (e.g. `Deploy a Python API to Posit Connect [v1.8.2+], Posit Cloud, or shinyapps.io.`. It is unclear to users what a "Python API" is.
- This can be done so that backwards compatibility is not broken, but we only document and recommend `rsconnect deploy flask`.

### PR DESCRIPTION
**Pull request by tdstein**
## Intent

Renames commands using the `api` nomenclature to use `flask` instead.

Closes #491 

## Type of Change

- [ ] Bug Fix            
- [x] New Feature       
- [ ] Breaking Change   

## Approach

This change adds the `flask` target to the `deploy` and `write-manifest` commands and deprecates the `api` target. Since `api` is designed for `flask` functionality, a new AppMode is not required. Instead, the `AppModes.PTYHON_API` is reused.

The existing `api` commands are marked as deprecated to ensure backward compatibility.

## Automated Tests

Existing tests for the `api` command are refactored to use `flask`.

## Directions for Reviewers

- Try deploying an application using `deploy flask`.
- Try writing a manifest using `write-manifest flask`.

## Checklist

- [ ] I have updated [CHANGELOG.md](../CHANGELOG.md) to cover notable changes.
- [ ] I have updated all related GitHub issues to reflect their current state.

### CODE REVIEW

**Review by mmarchetti — APPROVED** [review]
Looks good. TIL about click's `deprecated` flag.

**Comment by kgartland-rstudio** [comment]
since we have a `fastapi` deployment type should this instead be `flaskapi`?

**Comment by aronatkins** [comment]
We have used the `rsconnect deploy api` command for other types, including Bottle, Falcon, pycnic, and simple WSGI applications. Are we explaining that the `flask` subcommand is still appropriate for these other types?

Should we continue to allow `api` as a not-deprecated command? I appreciate that the `flask` command makes Flask deployment more discoverable, but we're left with a different type of ambiguity for the remaining targets.

**Comment by tdstein** [comment]
> We have used the `rsconnect deploy api` command for other types, including Bottle, Falcon, pycnic, and simple WSGI applications. Are we explaining that the `flask` subcommand is still appropriate for these other types?
> 
> Should we continue to allow `api` as a not-deprecated command? I appreciate that the `flask` command makes Flask deployment more discoverable, but we're left with a different type of ambiguity for the remaining targets.

Oh - I did not know that. I was working under the assumption that it only deployed Flask applications.

Let me make another pass taking this into account.

**Comment by tdstein** [comment]
See @aronatkins's comment above. I will open a new pull request when that work is ready.

**Comment by aronatkins** [comment]
@tdstein - you may want to also coordinate with the posit.cloud folks in case they have documentation that needs updating. I did a quick look at https://posit.cloud/learn/guide, but may have missed something.

**Pull request closed without merging**
